### PR TITLE
Add ability to insert variables if they don't exist in serverless.yml, fix readme, and logic cleanup

### PR DESCRIPTION
**Pull request by couchcryptid**
- Fix logic to insert variables if they don't exist, fix readme to reference correct package
- Remove unused log params, add dotenv and dotenv-expand to dependencies for cleaner parsing script

### CODE REVIEW

**Comment by apancutt** [comment]
It is by design that parameters are not added by this package, only modified.

Usually there is a design flaw if an app requires additional params in specific environments. This tends to eventually spawn bugs that are hard to diagnose.

Can you give an example where you would want such behaviour? Perhaps there is a valid use case.

**Comment by couchcryptid** [comment]
In the case of a host like Lambda (or if you're using a build server), you should be using their tools to inject in your environment variables into the app and not committing them as part of your repository. If you're doing that, then you're only putting placeholder environment variables into your serverless.yml and that violates DRY.

It's less about adding in environment variables that don't exist elsewhere and more about keeping your environment variables secure.

**Comment by apancutt** [comment]
Sorry, I still don't follow.

How are you creating Serverless-managed Lambdas with env vars that are not declared in serverless.yml?

I understand why a build server might want to override values but don't see why it would need to add/remove env vars.

> placeholder environment variables into your serverless.yml and that violates DRY

I disagree. While having all the env vars explicitly defined in a consistent way (typically in `serverless.yml`) may cause some repetition/redundancy I would argue that any extraneous entries (placeholders) serve a documentation purpose which would not violate DRY as there is a legitimate purpose for the duplication.

If you don't explicitly declare all your env vars in your `serverless.yml` (where a Serverless dev would expect to find them) then you'll be leaving the next developer wondering where the env comes from, how did it get there and what uses it. This at best wastes some time, but at worst can bring systems down.

Are you able to share your exact use case?

**Comment by couchcryptid** [comment]
> How are you creating Serverless-managed Lambdas with env vars that are not declared in serverless.yml?

I possibly could be misreading the documentation, but it seems you would be able to just create them in the console. https://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

> I disagree. While having all the env vars explicitly defined in a consistent way (typically in serverless.yml) may cause some repetition/redundancy I would argue that any extraneous entries (placeholders) serve a documentation purpose which would not violate DRY as there is a legitimate purpose for the duplication.
>
> If you don't explicitly declare all your env vars in your serverless.yml (where a Serverless dev would expect to find them) then you'll be leaving the next developer wondering where the env comes from, how did it get there and what uses it. This at best wastes some time, but at worst can bring systems down.

So my understanding is instead of using a .env.dist (or something) file that contains the env variable keys, you're inserting the keys into the serverless.yml file? I guess I can see that.

My specific use case is trying to avoid uploading credentials into the repository.

**Comment by apancutt** [comment]
> I possibly could be misreading the documentation, but it seems you would be able to just create them in the console. https://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

So you deploy the function using `sls deploy` and then push environment variables to the newly-created Lambda using AWS CLI? If so, I would advise against that.

> you're inserting the keys into the serverless.yml file?

Yes, all vars should be defined in serverless.yml using hard-coded values or one of the [sources supported by Serverless](https://serverless.com/framework/docs/providers/aws/guide/variables/).

> My specific use case is trying to avoid uploading credentials into the repository.

Using [SSM as the source](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store) is ideal for this.

```yaml
# serverless.yml

service: myservice
provider:
  name: aws
  environment:
    MY_PASSWORD: ${ssm:myPassword}
```

```yaml
# .env
MY_PASSWORD: mydevpassword
```

You would need to add `myPassword` to SSM first. You can do this via the AWS Console or through AWS CLI:

`aws ssm put-parameter --name myPassword --value "secret" --type String` ¹

¹ You should really use the `SecureString` type for sensitive data but that requires a little more work to set up so refer the docs.

**Comment by apancutt** [comment]
I have extracted the parts of this PR that fixes issues with the README, but will now close this PR for reasons discussed above.

**Pull request closed without merging**
